name: Deploy Frontend to Test VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            FRONT_DIR="/var/www/bozor_test_front"
            REPO_URL="git@github.com:username/bozor_nest.git"
            BRANCH="dev"

            # Check if folder exists and is not empty
            if [ ! -d "$FRONT_DIR" ] || [ -z "$(ls -A $FRONT_DIR)" ]; then
              echo "Folder is missing or empty. Cloning repository..."
              git clone --branch $BRANCH --single-branch $REPO_URL $FRONT_DIR
            else
              echo "Folder exists. Pulling latest changes..."
              cd $FRONT_DIR
              git reset --hard
              git pull origin $BRANCH
            fi

            # Build frontend
            cd $FRONT_DIR
            npm install
            npm run build

            # Reload only test-myrent backend
            pm2 reload ecosystem.config.js --only test-myrent
