name: Deploy Frontend to Test VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            FRONT_DIR="/var/www/bozor_test_front"
            REPO_URL="https://github.com/valievswe/myrent_front.git"
            BRANCH="dev"
            NODE_VERSION="24"
            
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use $NODE_VERSION || nvm install $NODE_VERSION
            
            if [ ! -d "$FRONT_DIR" ] || [ ! -d "$FRONT_DIR/.git" ]; then
            rm -rf $FRONT_DIR
            git clone --branch $BRANCH --single-branch $REPO_URL $FRONT_DIR
            fi
            
            cd $FRONT_DIR
            git fetch origin $BRANCH
            git reset --hard origin/$BRANCH
            
            npm install
            npm run build
            
            find . -mindepth 1 -maxdepth 1 ! -name dist ! -name .git -exec rm -rf {} +
            
            echo "Current folder:"
            pwd
            echo "Contents:"
            ls -la


